# Generated by Django 4.1.4 on 2022-12-11 15:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateFinish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=models.DateTimeField(default=django.utils.timezone.now)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='dateStart',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=models.DateTimeField(default=django.utils.timezone.now)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
