# Generated by Django 4.1.4 on 2022-12-11 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task_datefinish_task_datestart_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateStart',
            field=models.DateTimeField(auto_now_add=True, verbose_name=models.DateTimeField(default=django.utils.timezone.now)),
        ),
    ]
