# Generated by Django 4.1.4 on 2022-12-11 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_task_datestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateStart',
            field=models.DateTimeField(verbose_name=models.DateTimeField(default=django.utils.timezone.now)),
        ),
    ]
